name: cassowary
version: 0.4.1
description: An implementation of the Cassowary constraint solving algorithm in Dart.
homepage: https://github.com/google/cassowary.dart/
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  lints: ^1.0.1
  matcher: ^0.12.11
  test: ^1.17.11
